site_name: 动态规划
site_url: https://mudrock51.github.io/Kris4js-algorithm-Web/

theme: 
    name: material

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - js/mathjax-config.js
